---

version: '3.8'

services:
  app:
    working_dir: /var/local/app/
    image: golang:1.16-buster
    volumes:
      - type: volume
        source: go-pkg
        target: /go/pkg
      - type: volume
        source: go-bin
        target: /go/bin
      - type: bind
        source: ${PWD}/app/
        target: /var/local/app/
    ports:
      - 8080:8080
volumes:
  go-pkg:
  go-bin:
